### ISSUE TITLE
Timer clear

### ISSUE THREAD

**Issue by yunsonbai** [cyberdelia/metrology#21]
i use the tMetrology.timer('sss')
after i use timer.clear(),  the timer.min=0 always， No change

**Comment by cyberdelia** [comment]
``clear`` will actually reset the timer.
So you want either to use in a context manager or using ``update``:

```python
timer = Metrology.timer('responses')
with timer:
    do_something()
```

**Comment by yunsonbai** [comment]
I first use clear. then I use the update, but the timer.min has not changed, always 0
