### ISSUE TITLE
Decorators don't allow for return values

### ISSUE THREAD

**Issue by steven-lai** [cyberdelia/metrology#34]
```
@Metrology.timer('test')
def test():
  return 'test'

print(test())
```

Expected output is `test` but instead `None` is printed.

I believe the relevant code in `metrology.instruments.meter.Meter`:

```
    def __call__(self, *args, **kwargs):
        if args and hasattr(args[0], '__call__'):
            _orig_func = args[0]
            def _decorator(*args, **kwargs):
                with self:
                    _orig_func(*args, **kwargs)
            return _decorator
```

It should say `return _orig_func(*args, **kwargs)` instead, maybe?

Using `metrology 1.2.2` with `Python 2.7.13`

**Comment by steven-lai** [comment]
My current workaround is:

```
def test():
  with Metrology.timer('test'):
    return 'test'
```

**Comment by cyberdelia** [comment]
@steven-lai Looks like so, would you mind making a PR for both meter and timer?

**Comment by steven-lai** [comment]
@cyberdelia PR submitted - https://github.com/cyberdelia/metrology/pull/35

**Comment by steven-lai** [comment]
@cyberdelia I saw you released `1.2.3` and I assume this change is in there, please correct me if I'm wrong.

Upon  updating to `1.2.3`, I'm still seeing the same issue:

- I did clean install by uninstalling it first (`pip uninstall metrology`) and re-installing
- I downloaded the wheel and examined the contents found at https://pypi.python.org/pypi/metrology

**Comment by cyberdelia** [comment]
@steven-lai Try with 1.2.4?

**Comment by steven-lai** [comment]
Downloaded the wheel, unpacked, and verified the code has the changes. Thanks!
